services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    App\Messenger\Redis:
        arguments: ['%app.messenger.redis.url%', '%app.messenger.redis.port%', '%app.messenger.redis.serializer%']
    App\Messenger\Command\ListMessengerReceivers:
        arguments:
          - []
        tags: [ { name: console.command } ]
